### ISSUE TITLE
"Captcha answer is missing" error (v1.2.0)

### ISSUE THREAD

**Issue by YasarYY** [SharkyKZ/joomla-recaptcha-v3-plugin#13]
Hi,
Plugin v1.2.0, with trigger method "On Page Load" selected, at Joomla v‎5.2.2, and using with RSContact! form, always gives error "Captcha answer is missing. Note that JavaScript is required to submit the form." when the form is submitted.
When trigger method is changed to "On Form Submit", same error is given, but in addition, even when form's required fields are not filled, whole page still refreshes, as if submit code failed and page refreshed as the original html form submit behavior (but not actually submitted). This was already the case for me even before plugin update v1.2.0.

**Comment by SharkyKZ** [comment]
RSContact is not supported because it does not use the Captcha API correctly. Although it's possible to use a dirty workaround in the plugin, I'd rather not do that, it should be fixed in RSContact. If you care to report this to them, this is the change they need to make in `helper.php`:

```
-- if ($show_captcha && !self::captchaGenerate('onCheckAnswer', null, $module->id)) {
++ if ($show_captcha && !self::captchaGenerate('onCheckAnswer', $jInput->get('mod-rscontact-captcha-' . $module->id, null, 'RAW'), $module->id)) {
```

**Comment by YasarYY** [comment]
Thank you for your response. I tried the code change at my site, with different filters, but I always got below error at the page with the form. Message is just displayed on screen and I cannot find any error log, so I cannot find root cause. Do you may be have any further advice? I want to have a working solution before reporting the case to RSContact.

syntax error, unexpected token "catch", expecting "function" or "const"

**Comment by SharkyKZ** [comment]
I think you pasted the whole code snippet. What the snippet meant to indicate is that this line:

    if ($show_captcha && !self::captchaGenerate('onCheckAnswer', null, $module->id)) {
Needs to be changed to this:

    if ($show_captcha && !self::captchaGenerate('onCheckAnswer', $jInput->get('mod-rscontact-captcha-' . $module->id, null, 'RAW'), $module->id)) {

**Comment by YasarYY** [comment]
Nope, I added one line from your suggestion, and commented out the other. I don't see any syntax error at the line or at try/catch blocks. Seems like some exception is thrown somewhere but not properly handled, but I don't know how to trace, since I cannot find any error logs.

I may consider installing a server at my local computer and try to debug.

**Comment by SharkyKZ** [comment]
I've attached the `helper.php`...
[helper.php.txt](https://github.com/user-attachments/files/18004978/helper.php.txt)
